-- Website visitor inbox. Separate from sg_engager_inbox.
-- Inserts only via gl-visitor-hook. Pipeline does not claim these rows.

CREATE TABLE IF NOT EXISTS public.sg_visitor_inbox (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  received_at timestamptz NOT NULL DEFAULT now(),
  dedupe_key text NOT NULL UNIQUE,
  visitor_id text,
  site_id text,
  first_name text,
  last_name text,
  full_name text,
  email text,
  phone text,
  linkedin_url text,
  job_title text,
  company_name text,
  company_domain text,
  company_employees text,
  page_url text,
  visited_at timestamptz,
  city text,
  country text,
  campaign_id bigint,
  campaign_name text,
  lane text NOT NULL DEFAULT 'visitor',
  status text NOT NULL DEFAULT 'received',
  routing_note text,
  slack_ts text,
  match jsonb,
  raw jsonb NOT NULL
);

CREATE INDEX IF NOT EXISTS sg_visitor_inbox_status_id_idx
  ON public.sg_visitor_inbox (status, id);

CREATE INDEX IF NOT EXISTS sg_visitor_inbox_email_lower_idx
  ON public.sg_visitor_inbox (lower(email));

CREATE INDEX IF NOT EXISTS sg_visitor_inbox_received_at_idx
  ON public.sg_visitor_inbox (received_at DESC);

ALTER TABLE public.sg_visitor_inbox ENABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.sg_visitor_inbox TO service_role;
